# Generated by Django 5.2.6 on 2025-09-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='verification_code',
        ),
    ]
