# Generated by Django 5.2.6 on 2025-09-08 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_userinfo_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
