# Generated by Django 5.2.6 on 2025-09-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_template_description_template_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='template',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='slug',
        ),
        migrations.AddField(
            model_name='template',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
