# Generated by Django 5.2.6 on 2025-09-08 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_education_id_alter_language_id_alter_skill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(['html'])]),
        ),
    ]
